from __future__ import annotations

from typing import Any


def multi_section_print_estimate() -> dict[str, Any]:
    """Estimate fixture covering every Modern print section and total path."""
    return {
        "header": {
            "voucher_no": "EST-PARITY-001",
            "date": "2026-07-19",
            "silver_rate": 101.25,
            "note": "Parity fixture",
            "last_balance_silver": 2.75,
            "last_balance_amount": 1250.50,
        },
        "items": [
            {
                "item_code": "REG001",
                "item_name": "Chain Deluxe",
                "gross": 200.34,
                "poly": 0.25,
                "net_wt": 200.09,
                "purity": 92.5,
                "wage_rate": 15.75,
                "pieces": 2,
                "fine": 185.08325,
                "wage": 190.42,
                "is_return": 0,
                "is_silver_bar": 0,
            },
            {
                "item_code": "REG002",
                "item_name": "Anklet Pair",
                "gross": 150.875,
                "poly": 0.125,
                "net_wt": 150.75,
                "purity": 90.0,
                "wage_rate": 12.0,
                "pieces": 4,
                "fine": 135.675,
                "wage": 105.0,
                "is_return": 0,
                "is_silver_bar": 0,
            },
            {
                "item_code": "BAR100",
                "item_name": "Silver Bar 100g",
                "gross": 100.0,
                "poly": 0.0,
                "net_wt": 100.0,
                "purity": 99.9,
                "wage_rate": 0.0,
                "pieces": 1,
                "fine": 99.9,
                "wage": 0.0,
                "is_return": 0,
                "is_silver_bar": 1,
            },
            {
                "item_code": "BAR050",
                "item_name": "Silver Bar 50g",
                "gross": 50.0,
                "poly": 0.0,
                "net_wt": 50.0,
                "purity": 99.5,
                "wage_rate": 0.0,
                "pieces": 1,
                "fine": 49.75,
                "wage": 0.0,
                "is_return": 0,
                "is_silver_bar": 1,
            },
            {
                "item_code": "RET001",
                "item_name": "Return Ring",
                "gross": 4.5,
                "poly": 0.1,
                "net_wt": 4.4,
                "purity": 91.6,
                "wage_rate": 8.0,
                "pieces": 1,
                "fine": 4.0304,
                "wage": 35.0,
                "is_return": 1,
                "is_silver_bar": 0,
            },
            {
                "item_code": "RET002",
                "item_name": "Return Chain",
                "gross": 6.25,
                "poly": 0.25,
                "net_wt": 6.0,
                "purity": 92.5,
                "wage_rate": 7.5,
                "pieces": 1,
                "fine": 5.55,
                "wage": 45.0,
                "is_return": 1,
                "is_silver_bar": 0,
            },
            {
                "item_code": "RBAR020",
                "item_name": "Return Silver Bar",
                "gross": 20.0,
                "poly": 0.0,
                "net_wt": 20.0,
                "purity": 99.9,
                "wage_rate": 0.0,
                "pieces": 1,
                "fine": 19.98,
                "wage": 0.0,
                "is_return": 1,
                "is_silver_bar": 1,
            },
        ],
    }


__all__ = ["multi_section_print_estimate"]
