import pytest
from argon2 import PasswordHasher

from silverestimate.security.password_service import (
    MalformedPasswordHashError,
    PasswordHashService,
)

SYNTHETIC_PASSWORD = "synthetic-main-password"

# Generated by Passlib 1.7.4's Argon2id handler with the application's former
# m=65536, t=3, p=4 policy and a fixed synthetic salt.
PASSLIB_CURRENT_POLICY_HASH = (
    "$argon2id$v=19$m=65536,t=3,p=4$c3ludGhldGljLXNhbHQhIQ$"
    "FX332B9UqVYkQQBqgo/RIhU0EiPnwKVjvSXVXSgSYc8"
)

# Generated by the same Passlib handler with an older, lower-cost policy.
PASSLIB_OLD_POLICY_HASH = (
    "$argon2id$v=19$m=8192,t=2,p=1$c3ludGhldGljLW9sZCEhIQ$"
    "UjcniriXIc6HI2cGv97flo3H+AWgkPcN9wvr1S+BTG4"
)


def test_hash_password_uses_explicit_argon2id_policy() -> None:
    password_service = PasswordHashService()

    password_hash = password_service.hash_password(SYNTHETIC_PASSWORD)

    assert password_hash.startswith("$argon2id$v=19$m=65536,t=3,p=4$")
    assert PasswordHasher().verify(password_hash, SYNTHETIC_PASSWORD)


def test_passlib_current_policy_hash_remains_compatible() -> None:
    password_service = PasswordHashService()

    verification = password_service.verify_password(
        PASSLIB_CURRENT_POLICY_HASH,
        SYNTHETIC_PASSWORD,
    )

    assert verification.verified
    assert verification.replacement_hash is None


def test_passlib_old_policy_hash_is_upgraded_after_successful_verification() -> None:
    password_service = PasswordHashService()

    verification = password_service.verify_password(
        PASSLIB_OLD_POLICY_HASH,
        SYNTHETIC_PASSWORD,
    )

    assert verification.verified
    assert verification.replacement_hash is not None
    assert verification.replacement_hash.startswith("$argon2id$v=19$m=65536,t=3,p=4$")
    assert password_service.verify_password(
        verification.replacement_hash,
        SYNTHETIC_PASSWORD,
    ).verified


def test_wrong_password_is_an_expected_mismatch() -> None:
    verification = PasswordHashService().verify_password(
        PASSLIB_CURRENT_POLICY_HASH,
        "wrong-password",
    )

    assert not verification.verified
    assert verification.replacement_hash is None


@pytest.mark.parametrize("stored_hash", ["", "not-a-password-hash", "$argon2id$bad"])
def test_malformed_hash_is_distinct_from_password_mismatch(stored_hash: str) -> None:
    with pytest.raises(MalformedPasswordHashError):
        PasswordHashService().verify_password(stored_hash, SYNTHETIC_PASSWORD)


def test_empty_password_is_rejected_for_new_hashes() -> None:
    with pytest.raises(ValueError, match="must not be empty"):
        PasswordHashService().hash_password("")
