name: Release Windows

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm silverestimate.spec

      - name: Archive build
        shell: pwsh
        run: |
          $version = (Get-Content app_constants.py | Select-String -Pattern 'APP_VERSION\s*=\s*"([^"]+)' -AllMatches).Matches.Groups[1].Value
          if (-not $version) { $version = "dev" }
          $zipName = "SilverEstimate-v$version-win64.zip"
          if (Test-Path "dist/$zipName") { Remove-Item "dist/$zipName" -Force }
          Compress-Archive -Path "dist/SilverEstimate/*" -DestinationPath "dist/$zipName"
          "ZIP_NAME=$zipName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: |
            dist/${{ env.ZIP_NAME }}
            dist/*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ env.ZIP_NAME }}
            dist/*.zip
