name: Release Windows

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable (OneFile)
        run: |
          python -m PyInstaller --noconfirm --onefile --windowed --name SilverEstimate --hidden-import passlib.handlers.argon2 --hidden-import passlib.handlers.bcrypt main.py

      - name: Rename executable with version and package artifact
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $tag = "${{ github.ref_name }}"
          $exeSrc = "dist\SilverEstimate.exe"
          if (!(Test-Path $exeSrc)) { throw 'Build did not produce dist\\SilverEstimate.exe' }
          $exeDst = "dist\SilverEstimate-$tag.exe"
          Move-Item -Force -Path $exeSrc -Destination $exeDst
          $zipName = "SilverEstimate-$tag-win64.zip"
          if (Test-Path $zipName) { Remove-Item -Force $zipName }
          Compress-Archive -Path $exeDst -DestinationPath $zipName

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SilverEstimate-${{ github.ref_name }}-win64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
